// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQtC-bs2ki87zwQNphXT9XFrcuQtM99U',
    appId: '1:695488149221:web:0d104fb7aba6776ebec60c',
    messagingSenderId: '695488149221',
    projectId: 'krishiraksha-642b6',
    authDomain: 'krishiraksha-642b6.firebaseapp.com',
    storageBucket: 'krishiraksha-642b6.firebasestorage.app',
    measurementId: 'G-MDJDKP606M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa6CrSi8Bsj6Ukb3vWB5pudavuor55AxY',
    appId: '1:695488149221:android:9ce977cf60c63a75bec60c',
    messagingSenderId: '695488149221',
    projectId: 'krishiraksha-642b6',
    storageBucket: 'krishiraksha-642b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJv9G8WZcySLroX3Ks-PF5LUvm-yZnKc8',
    appId: '1:695488149221:ios:b99abb13017d58e3bec60c',
    messagingSenderId: '695488149221',
    projectId: 'krishiraksha-642b6',
    storageBucket: 'krishiraksha-642b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJv9G8WZcySLroX3Ks-PF5LUvm-yZnKc8',
    appId: '1:695488149221:ios:b99abb13017d58e3bec60c',
    messagingSenderId: '695488149221',
    projectId: 'krishiraksha-642b6',
    storageBucket: 'krishiraksha-642b6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKQtC-bs2ki87zwQNphXT9XFrcuQtM99U',
    appId: '1:695488149221:web:45206fa21828f15dbec60c',
    messagingSenderId: '695488149221',
    projectId: 'krishiraksha-642b6',
    authDomain: 'krishiraksha-642b6.firebaseapp.com',
    storageBucket: 'krishiraksha-642b6.firebasestorage.app',
    measurementId: 'G-5YJ00VRBVG',
  );

}